### PR TITLE
Update document.csv

### PR DESCRIPTION
**Pull request by maxw0206**
Manx proof-read, and original spelling restored. I think we should restore Britannicus's English original in the English column.

### CODE REVIEW

**Comment by david-allison-1** [comment]
> Manx proof-read, and original spelling restored. I think we should restore Britannicus's English original in the English column.

Nothing wrong with having 3 columns and moving Rob's to a third (if that's what the consensus is) 

I'll add in a pending issue to look into this

**Comment by maxw0206** [comment]
But then, what is the value of Rob’s version supposed to be, if the Manx is itself a translation of the English original?

 

Max

 

303-304 Admirals Court

Mooragh Promenade

Ramsey

Isle of Man IM8 3AY

British Isles

 

Tel: +44 (0)1624 814402

Mobile: +44 (0)7624 378765

Email:  ***@***.***> ***@***.***

**Comment by david-allison-1** [comment]
Ah - wasn't aware it was E -> M to start with. Definitely replace then

**Comment by maxw0206** [comment]
OK. I'll edit BRITANNICUS's English from the newspaper, as I have done with the "Actor rendering a Written Memorandum".

**Review by david-allison-1 — APPROVED** [review]

**Comment by david-allison-1** [comment]
Sounds good. It's likely simpler to add a comment to the issue: https://github.com/david-allison-1/manx-search-data/issues/695

with the translation in a `docx` table, rather than editing inline in the GitHub editor.

**Comment by maxw0206** [comment]
I don't understand about _forks_ and _branches_. Is there a simple explanation?

Will add English text in .docx table to #695.

**Comment by david-allison-1** [comment]
> I don't understand about _forks_ and _branches_. Is there a simple explanation?
> 
> Will add English text in .docx table to #695.

I've had a look through the simple guides, and didn't feel any of them were sufficient.

* git works like "track changes" in Word, but over a folder of files, allowing thousands of people to be working on the same folders, without needing access to an internet connection. 
* It works by providing the "good" history of the project (`master`) to everyone, and changes are made using this as a starting point.
   * A history is a list of changes (`commits`). Anyone can look back in history to see how things were (to recover from errors, or to understand why a change to a file was made).
* `master` is the master record, where the current "good" copy of work is. For `manx-search-data`, the website's data is replaced with what's on `master` daily (4AM). 
   * Everything on https://manxcorpus.com/ (aside from the URL) comes from GitHub, and can be replicated by anyone.
* A branch is a copy of `master` at a given time. You can make one or more changes (`commits`) to a branch
   * There's no limit to the number of branches
* A branch is merged back into `master` via a `pull request`
  * A pull request lets us run automated checks to confirm the data is OK, and discuss the changes made
* A `fork` is your personal copy of all of the data for the site.
   * This is where branches can be created. Forks are entirely yours, so changes can be made without anyone affecting your work.

image

----

* In a word document (I think) you have a linear history: if you do some work on a section, fix some typos, and then someone doesn't like the section changes that you've made, they can't undo the changes to section 2 without undoing the typo fixes.
* Branches allow each "type" of change to be handled individually, if there's a change which requires discussion, then everyone can continue work while this discussion takes place, and the person proposing the change can quickly move onto other changes. Most branches are short-lived (hours)

----

These may also be of use:


https://docs.github.com/en/get-started/quickstart/github-glossary#repository
https://docs.github.com/en/get-started/quickstart/github-glossary#master
https://docs.github.com/en/get-started/quickstart/github-glossary#branch
https://docs.github.com/en/get-started/quickstart/github-glossary#fork

**Comment by maxw0206** [comment]
Hi David
Many thanks for taking the trouble to explain the terminology, and  something of the structure. At least I know what "Track changes" in Word means, and how to use it, which not everyone who works in Word does :-).

**Pull request merged**
